### ISSUE TITLE
Hacer Video de la Propuesta

### ISSUE THREAD

**Issue by Armandotrsg** [Armandotrsg/SpaceShooter#12]
- Acabar lo del checkpoint 1 (ya es poco)
- Hacer el video de la propuesta

Link del Docs:
https://docs.google.com/document/d/1ZT_y074hKudGIql00NBh0v_WJ9RkFbudHZJ3wzQacaM/edit?usp=sharing

**Comment by HeberM69** [comment]
Ya quedó el video <3
